--- #YAML:1.0
name:                Sysadm-Install
version:             0.23
abstract:            Typical installation tasks for system administrators
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Cwd:                           0
    File::Basename:                0
    File::Copy:                    0
    File::Path:                    0
    File::Temp:                    0.16
    Log::Log4perl:                 1
    LWP::Simple:                   0
    Term::ReadKey:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <m@perlmeister.com>
