--- #YAML:1.0
name:               Sysadm-Install
version:            0.38
abstract:           Typical installation tasks for system administrators
author:
    - Mike Schilli <m@perlmeister.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cwd:             0
    File::Basename:  0
    File::Copy:      0
    File::Path:      0
    File::Temp:      0.16
    Log::Log4perl:   1.28
    LWP::Simple:     0
    Term::ReadKey:   0
resources:
    repository:  http://github.com/mschilli/sysadm-install-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
