---
abstract: 'Typical installation tasks for system administrators'
author:
  - 'Mike Schilli <m@perlmeister.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sysadm-Install
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 0
  File::Temp: 0.16
  LWP::Simple: 0
  Log::Log4perl: 1.28
  Term::ReadKey: 0
resources:
  repository: http://github.com/mschilli/sysadm-install-perl
version: 0.40
