# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sysadm-Install
version:      0.04
version_from: lib/Sysadm/Install.pm
installdirs:  site
requires:
    File::Basename:                
    File::Copy:                    
    File::Path:                    
    Log::Log4perl:                 
    Cwd:
    Archive::Tar:
    LWP::Simple:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
